id: P009146
initial_creation_type: ocr
created_at: 22/03/2020
last_modified_at: 25/11/2021
source_metadata:
  id: bdr:W1KG22578
  title: འཕན་པོ་ན་ལེནྡྲ་པའི་ཆོས་སྤྱོད།
  author: ''
  volumes:
    e96afc4ec80b4f0095f42d39c5c286e7:
      image_group_id: I1KG22599
      title: ''
      volume_number: 1
      total_pages: 454
      base_file: v001.txt
